
export const Constants = {

  TEST_MSG: 'Test message',

  SUCCESS: 0,

  // ! 后端的信息码定义
  USERS_SIGNUP_IDENTITY_NOT_EXISTING: 201,
  USERS_SIGNUP_IDENTITY_EXISTING: 202,
  USERS_SIGNUP_EMAIL_NOT_EXISTING: 203,
  USERS_SIGNUP_EMAIL_EXISTING: 204,

  USERS_ACTIVATE_IDENTITY_NOT_EXISTING: 211,
  USERS_ACTIVATE_USER_BEEN_ACTIVATED: 212,
  USERS_ACTIVATE_INPUT_EMAIL_INVALID: 213,
  USERS_ACTIVATE_GEN_CODE_FAILED: 214,
  USERS_ACTIVATE_SEND_MAIL_FAILED: 215
}
