
export const Constants = {

  TEST_MSG: 'Test message',
  AUTH_SUCCESS: 0,
  AUTH_FAILED: -1,

  AUTH_REGISTER_DUPLICATED_IDENTITY: 1,
  AUTH_REGISTER_NEWUSER_FAILED: 2,

  AUTH_LOGIN_EXCEED_ATTEMPTS: 2,
  AUTH_LOGIN_USER_NOT_EXIST: 3,
  AUTH_LOGIN_INVALID_PASSWORD: 4,
  AUTH_LOGIN_USER_NOT_ACTIVE: 5,

  AUTH_TOKEN_SIGNATURE_INVALID: 1,
  AUTH_TOKEN_PAYLOAD_INVALID: 2

}
